phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - "./gradlew build"
      - mv build/libs/spring-hello.war ROOT.war
artifacts:
  files:
    - ROOT.war
    - .ebextensions/**/*